# Site settings
title: GeoDa Data and Lab
description: GeoDa site for Data and Labs
baseurl: "/data-and-lab/" # the subpath of your site, e.g. /blog
url: "https://geodacenter.github.io/data-and-lab/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: GeoDa
user_description: GeoDa Data and Lab
email: spatial@uchicago.edu
twitter_username: geodacenter
github_username:  geodacenter
gplus_username:  geodacenter
disqus_username: geodacenter

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  #- title: Series
  #  url: /series
  - title: Tags
    url: /tags
  #- title: About Us
  #  url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

includes:
- data
